import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { Presentation, PresentationFile } from "@oai/artifact-tool";

const SKILL_DIR = "C:/Users/Jern Fey/.codex/plugins/cache/openai-primary-runtime/presentations/26.904.11930/skills/presentations";
const workspaceDir = "C:/Users/Jern Fey/fyp2";
const TMP_DIR = path.join(workspaceDir, ".build", "oral-presentation");
const FINAL_PPTX = path.join(workspaceDir, "output", "Robust_KMeans_Oral_Presentation_2206563.pptx");
const RUNTIME_PYTHON = "C:/Users/Jern Fey/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe";
const { resolvePresentationFont, applyPresentationChartFont, finalizePresentation } = await import(pathToFileURL(path.join(SKILL_DIR, "container_tools/artifact_tool_utils.mjs")).href);
const font = resolvePresentationFont({ fontFamily: "Aptos" });
const p = Presentation.create({ slideSize: { width: 1280, height: 720 } });

const C = { navy: "#10253F", blue: "#176B87", teal: "#3AAFA9", pale: "#EAF4F4", ink: "#14212B", grey: "#5C6973", gold: "#F2B84B", white: "#FFFFFF", red: "#C84949" };
const source = "Source: Lim Jern Fey, Robust Centroid Measurement for Improving K-means Clustering Accuracy (2026).";

function box(slide, text, x, y, w, h, opts = {}) {
  const s = slide.shapes.add({ geometry: "textbox", position: { left:x, top:y, width:w, height:h }, fill: opts.fill ?? "none", line: { fill: opts.line ?? "none", width:0 } });
  s.text = text;
  s.text.style = { typeface: font, fontSize: opts.size ?? 22, bold: opts.bold ?? false, color: opts.color ?? C.ink, autoFit: "shrinkText", verticalAlignment: opts.va ?? "top", ...(opts.align ? { alignment: opts.align } : {}) };
  return s;
}
function rect(slide, x,y,w,h, fill, radius=false) { return slide.shapes.add({ geometry: radius ? "roundRect" : "rect", position:{left:x,top:y,width:w,height:h}, fill, line:{fill, width:0} }); }
function title(slide, text, n) {
  box(slide, text, 68, 48, 1050, 52, {size: 34, bold:true, color:C.navy});
  box(slide, String(n).padStart(2,"0"), 1165, 54, 50, 30, {size:15,bold:true,color:C.teal,align:"right"});
  rect(slide,68,112,1144,4,C.teal);
}
function note(slide, more="") { slide.speakerNotes.textFrame.setText(`${source} ${more}`); }
function bullets(slide, items, x,y,w, size=22, color=C.ink) { items.forEach((t,i)=>{ rect(slide,x,y+i*54,10,10,C.teal,true); box(slide,t,x+25,y-5+i*54,w-25,42,{size,color}); }); }
function section(slide, label, x,y,w, h=36) { rect(slide,x,y,w,h,C.pale); box(slide,label,x+14,y+7,w-28,h-10,{size:16,bold:true,color:C.blue}); }
function process(slide, labels, y=310) { const start=82, gap=22, w=(1116-gap*(labels.length-1))/labels.length; labels.forEach((t,i)=>{ rect(slide,start+i*(w+gap),y,w,108, i===labels.length-1?C.teal:C.pale, true); box(slide,t,start+15+i*(w+gap),y+25,w-30,58,{size:20,bold:true,color:i===labels.length-1?C.white:C.navy,align:"center",va:"middle"}); if(i<labels.length-1) box(slide,"→",start+w+4+i*(w+gap),y+34,14,32,{size:25,bold:true,color:C.blue,align:"center"}); }); }

// 1
{ const s=p.slides.add(); s.background.fill=C.navy; rect(s,72,84,8,470,C.teal); box(s,"ROBUST CENTROID MEASUREMENT",112,138,1040,55,{size:27,bold:true,color:C.teal}); box(s,"Improving K-means\nClustering Accuracy",108,204,1000,155,{size:54,bold:true,color:C.white}); box(s,"Lim Jern Fey  |  2206563\nBachelor of Software Engineering (Honours)\nUniversiti Tunku Abdul Rahman",112,440,740,105,{size:22,color:"#DCE9EE"}); box(s,"Oral Presentation\nSeptember 2026",910,532,240,55,{size:18,color:C.gold,align:"right"}); note(s); }
// 2
{ const s=p.slides.add(); title(s,"Presentation overview",2); const items=[["1","Background and problem"],["2","Literature and research gap"],["3","Objectives and proposed solution"],["4","Method, evaluation and results"],["5","Demonstration, conclusion and future work"]]; items.forEach((a,i)=>{const y=160+i*86; rect(s,122,y,54,54,C.teal,true); box(s,a[0],122,y+12,54,30,{size:20,bold:true,color:C.white,align:"center"}); box(s,a[1],205,y+11,690,35,{size:26,bold:true,color:C.navy});}); box(s,"15 minutes presentation\n10-15 minutes system demonstration\n10 minutes Q&A",925,228,235,155,{size:21,bold:true,color:C.blue}); note(s); }
// 3
{ const s=p.slides.add(); title(s,"K-means clustering",3); box(s,"K-means partitions unlabelled data into k groups by repeatedly assigning each point to its nearest centroid, then recomputing centroids as arithmetic means.",90,157,1030,72,{size:27,color:C.navy}); process(s,["Initial centroids","Assign nearest centroid","Recompute means","Stop when stable"],310); box(s,"Why use it?",90,500,210,30,{size:20,bold:true,color:C.blue}); bullets(s,["Simple and computationally efficient","Scales to many numerical observations"],90,545,950,20); note(s,"Background and K-means workflow from Chapters 1 and 2."); }
// 4
{ const s=p.slides.add(); title(s,"Problem statement",4); section(s,"Centroid sensitivity",90,155,330); section(s,"Feature scale",475,155,330); section(s,"Distance choice",860,155,330); box(s,"Outliers pull the arithmetic mean away from the main group and distort cluster boundaries.",90,220,330,145,{size:23,color:C.ink}); box(s,"Features with large numerical ranges can dominate the distance calculation.",475,220,330,145,{size:23,color:C.ink}); box(s,"Different metrics create different assignments, and their effect depends on the dataset.",860,220,330,145,{size:23,color:C.ink}); rect(s,90,455,1100,105,C.navy,true); box(s,"Research question: How can preprocessing and distance selection improve K-means accuracy and stability without losing its simplicity?",125,480,1030,55,{size:27,bold:true,color:C.white,align:"center",va:"middle"}); note(s,"Problem statement from Chapter 1."); }
// 5
{ const s=p.slides.add(); title(s,"Literature review and research gap",5); box(s,"Existing work confirms that K-means is sensitive to outliers, scale, and distance measures. However, the benefit of each technique varies with the data.",85,148,1110,60,{size:27,color:C.navy}); section(s,"What literature establishes",100,270,450); bullets(s,["Outliers can shift mean-based centroids","Normalisation changes feature influence","Distance metrics alter cluster geometry"],100,325,450,20); section(s,"Gap addressed in this study",690,270,440); bullets(s,["Compare the three factors within one framework","Measure both accuracy and stability","Test configurations across nine benchmark datasets"],690,325,440,20); note(s,"Literature synthesis from Chapter 2; cited works include Jain (2010), Nowak-Brzezińska and Gaibei (2022), and Shrifan et al. (2022)."); }
// 6
{ const s=p.slides.add(); title(s,"Research objectives",6); const data=[["01","Outlier removal","Examine its impact on K-means performance."],["02","Data normalisation","Evaluate how scaling methods affect clustering results."],["03","Distance metrics","Analyse their impact on cluster formation and performance."]]; data.forEach((a,i)=>{const y=165+i*145; rect(s,105,y,85,85,C.teal,true); box(s,a[0],105,y+25,85,35,{size:24,bold:true,color:C.white,align:"center"}); box(s,a[1],230,y+5,480,34,{size:26,bold:true,color:C.navy}); box(s,a[2],230,y+49,760,47,{size:21,color:C.ink});}); note(s,"Research objectives from Section 1.4."); }
// 7
{ const s=p.slides.add(); title(s,"Proposed robust K-means configuration",7); box(s,"Candidate configuration selected after comparing preprocessing and distance options",90,145,1000,38,{size:25,color:C.grey}); process(s,["Robust Z-score\n2.5σ","Min-Max\nnormalisation","Euclidean\ndistance","K-means with\n30 restarts"],260); rect(s,150,470,980,92,C.navy,true); box(s,"Evaluate across 9 UCI datasets, repeat each configuration 100 times, and report accuracy, quality, and stability.",185,493,910,44,{size:25,bold:true,color:C.white,align:"center",va:"middle"}); note(s,"Proposed algorithm from Abstract and Chapters 3-4."); }
// 8
{ const s=p.slides.add(); title(s,"Experimental scope",8); box(s,"Nine UCI benchmark datasets",92,150,420,34,{size:27,bold:true,color:C.navy}); const rows=[["Iris","150","4","3"],["Glass","214","9","6"],["Balance","625","4","3"],["Cancer","569","30","2"],["Wine","178","13","3"],["Vertebral","310","6","2"],["Ecoli","336","7","8"],["Blood","748","4","2"],["Seeds","210","7","3"]]; const x=[90,330,515,710]; ["Dataset","Instances","Features","Clusters"].forEach((h,i)=>box(s,h,x[i],215,175,28,{size:17,bold:true,color:C.white,fill:C.blue})); rows.forEach((r,j)=>r.forEach((v,i)=>box(s,v,x[i],250+j*35,175,26,{size:17,color:C.ink,fill:j%2?C.pale:C.white}))); box(s,"Coverage",920,190,195,30,{size:25,bold:true,color:C.blue}); bullets(s,["150 to 748 instances","2 to 30 features","2 to 8 clusters","Balanced and imbalanced classes"],920,245,235,19); note(s,"Dataset summary from Table 3.1 / Appendix B."); }
// 9
{ const s=p.slides.add(); title(s,"Project plan",9); const phases=[["FYP1", "Literature review, requirements, experiment design",C.blue],["Early FYP2", "Implementation and benchmark experiments",C.teal],["Late FYP2", "Analysis, report writing, presentation",C.gold]]; phases.forEach((a,i)=>{const y=175+i*126; box(s,a[0],105,y+10,190,28,{size:22,bold:true,color:a[2]}); rect(s,325,y,760,66,a[2],true); box(s,a[1],350,y+20,700,28,{size:21,bold:true,color:i===2?C.navy:C.white});}); box(s,"The work plan moved from research design to repeated experiments, analysis, and final reporting.",105,580,1000,40,{size:24,color:C.navy}); note(s,"Project plan summarised from Chapter 3 and Appendix A work breakdown structure."); }
// 10
{ const s=p.slides.add(); title(s,"Development approach and tools",10); process(s,["Load UCI data","Preprocess\nvariants","Run custom\nK-means","Evaluate and\ncompare"],225); section(s,"Tools",120,470,250); bullets(s,["Python 3.12","NumPy, pandas","scikit-learn, SciPy","VS Code and Git/GitHub"],120,520,350,19); section(s,"Requirements",690,470,300); bullets(s,["Numerical UCI datasets","Known class labels for external evaluation","Repeatable random initialisation"],690,520,390,19); note(s,"Development tools from Table 3.3 / Appendix B and methodology from Chapter 3."); }
// 11
{ const s=p.slides.add(); title(s,"Evaluation design",11); const items=[["Internal quality","Inertia and Silhouette score"],["External agreement","ARI, NMI, Purity and Hungarian accuracy"],["Class performance","Precision, Recall and Macro-F1"],["Stability","Mean, standard deviation, minimum and maximum across 100 repetitions"]]; items.forEach((a,i)=>{const y=155+i*100; rect(s,105,y,330,70,i===0?C.navy:C.pale,true); box(s,a[0],125,y+20,290,28,{size:21,bold:true,color:i===0?C.white:C.navy,align:"center"}); box(s,a[1],480,y+19,620,32,{size:23,color:C.ink});}); note(s,"Evaluation metrics from Section 3.8."); }
// 12
{ const s=p.slides.add(); title(s,"Key results",12); box(s,"Proposed configuration achieved mean clustering accuracy of 0.82 across nine datasets.",88,145,1100,48,{size:29,bold:true,color:C.navy,align:"center"}); const chart=s.charts.add("bar",{position:{left:95,top:235,width:690,height:330},categories:["Iris","Glass","Balance","Cancer","Wine","Vertebral","Ecoli","Blood","Seeds"],series:[{name:"Hungarian accuracy",values:[0.8867,0.5984,0.5262,0.9301,0.9761,0.5256,0.6046,0.6448,0.8905],fill:C.teal}],barOptions:{direction:"column",grouping:"clustered"},hasLegend:false,dataLabels:{showValue:false}}); applyPresentationChartFont(chart,{fontFamily:font}); box(s,"Performance highlights",850,245,300,28,{size:23,bold:true,color:C.blue}); bullets(s,["Best or tied best on 4 of 9 datasets","Largest gains: Glass +0.16 and Ecoli +0.11","No single technique dominated every dataset"],850,295,310,18); note(s,"Results from Abstract, Tables 4.1 and 4.3. Chart uses Hungarian accuracy from Table 4.1."); }
// 13
{ const s=p.slides.add(); title(s,"Demonstration of the system",13); box(s,"Demonstration flow: run a dataset through the experimental pipeline and inspect the resulting metrics.",95,145,1080,44,{size:26,color:C.navy,align:"center"}); process(s,["Choose dataset","Select preprocessing","Run 30-restart K-means","Compare metrics and output"],260); box(s,"Suggested live example: Glass dataset",150,475,400,32,{size:25,bold:true,color:C.blue}); bullets(s,["Show the selected robust Z-score filter","Show Min-Max scaling and Euclidean distance","Run and compare against a baseline configuration"],150,535,850,20); note(s,"Demonstration plan based on the implemented experimental workflow in Chapter 3."); }
// 14
{ const s=p.slides.add(); title(s,"Conclusion, achievements and future work",14); section(s,"Conclusion",80,145,490); box(s,"Outlier removal, normalisation, and metric choice can improve K-means accuracy and stability, but the best configuration depends on the dataset.",80,200,490,130,{size:24,color:C.ink}); section(s,"Objectives achieved",700,145,420); bullets(s,["Evaluated outlier handling","Compared normalisation methods","Tested seven distance metrics"],700,205,420,19); section(s,"Future work",80,410,490); bullets(s,["Broader preprocessing methods and datasets","Alternative centroid updates","Study initialisation strategies such as k-means++"],80,465,490,19); box(s,"Thank you - Questions?",700,475,420,50,{size:30,bold:true,color:C.navy,align:"center"}); note(s,"Conclusion and future work from Chapter 5."); }

await fs.mkdir(TMP_DIR,{recursive:true});
const candidatePath=path.join(TMP_DIR,"candidate.pptx");
await (await PresentationFile.exportPptx(p)).save(candidatePath);
await fs.mkdir(path.dirname(FINAL_PPTX),{recursive:true});
const result=await finalizePresentation({workspaceDir,candidatePath,finalPath:FINAL_PPTX,pythonExecutable:RUNTIME_PYTHON,integrityValidatorPath:path.join(SKILL_DIR,"container_tools/inspect_presentation_package_integrity.py"),layoutValidatorPath:path.join(SKILL_DIR,"container_tools/inspect_presentation_layout_geometry.py"),layoutArgs:["--expected-slide-size-emu","12192000,6858000","--validate-bullet-geometry","--validate-heading-fit"],fontPolicy:{basis:"design",families:[font]},materializeLiteralChartWorkbooks:true,verifyArtifactToolImport:true,receiptPath:path.join(TMP_DIR,"validation.json")});
console.log(JSON.stringify({font,final:FINAL_PPTX,result},null,2));
